cudnn:                  # [linux64]
  - undefined           # [linux64]
cuda_compiler_version:  # [linux64]
  - None                # [linux64]
c_stdlib_version:       # [linux]
  - "2.17"              # [linux]
