{% set name = "util-linux" %}
{% set version = "2.40.2" %}
{% set major_minor = '.'.join(version.split('.')[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v{{ major_minor }}/util-linux-{{ version }}.tar.xz
  sha256: d78b37a66f5922d70edf3bdfb01a6b33d34ed3c3cafd6628203b2a2b67c8e8b3

build:
  number: 0
  skip: true  # [not unix]
  run_exports:
    - {{ pin_subpackage('util-linux', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - libtool
    - autoconf
    - automake
    - pkg-config
  host:
    - python
    - zlib
    - ncurses
    - readline
    - libuuid
    - libxcrypt  # [linux]
  run:
    - python

test:
  commands:
    - test -f "${PREFIX}/lib/libmount.so"  # [linux]
    - test -f "${PREFIX}/bin/hexdump"

about:
  home: https://en.wikipedia.org/wiki/Util-linux
  license: LGPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A random collection of Linux utilities
  dev_url: https://github.com/util-linux/util-linux

extra:
  recipe-maintainers:
    - jaimergp
    - scopatz
    - hmaarrfk
