{% set name = "util-linux" %}
{% set version = "2.37.2" %}
{% set major_version = version.split('.')[0] %}
{% set minor_version = version.split('.')[1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v{{ major_version }}.{{ minor_version }}/util-linux-{{ version }}.tar.xz
  sha256: 6a0764c1aae7fb607ef8a6dd2c0f6c47d5e5fd27aa08820abaad9ec14e28e9d9
  patches:
    - fix_missing_symbols_osx.patch  # [osx]
    - dont_test_procutils_osx.patch  # [osx]
build:
  number: 0
  skip: true  # [not unix]
  run_exports:
    - {{ pin_subpackage('util-linux', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - libtool
    - autoconf
  host:
    - python
    - zlib
    - ncurses
    - readline
    - libuuid   # [osx]
  run:
    - python
    - zlib
    - ncurses
    - readline

test:
  commands:
    - test -f "${PREFIX}/lib/libmount.so"  # [linux]
    - test -f "${PREFIX}/bin/hexdump"

about:
  home: https://en.wikipedia.org/wiki/Util-linux
  license: LGPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A random collection of Linux utilities
  dev_url: https://github.com/util-linux/util-linux

extra:
  recipe-maintainers:
    - scopatz
    - wolfv
