{% set name = "util-linux" %}
{% set version = "2.38.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v{{ version }}/util-linux-{{ version }}.tar.xz
  sha256: 6d111cbe4d55b336db2f1fbeffbc65b89908704c01136371d32aa9bec373eb64

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('util-linux', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python
    - zlib
    - ncurses
    - readline
  run:
    - python
    - zlib
    - ncurses
    - readline

test:
  commands:
    - test -f "${PREFIX}/lib/libmount.so"

about:
  home: https://en.wikipedia.org/wiki/Util-linux
  license: LGPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A random collection of Linux utilities
  dev_url: https://github.com/karelzak/util-linux

extra:
  recipe-maintainers:
    - scopatz
